FROM maven:3.9.6-eclipse-temurin

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src ./src

RUN mvn clean package -DskipTests

ENTRYPOINT ["java", "-jar", "target/AssessmentApplication-0.0.2-SNAPSHOT.jar"]
