name: My practice CICD pipeline

on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["main"]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                cache: "maven"
                distribution: "temurin"
                java-version: 17
            
            - name: Unit Test
              run: mvn test

            - name: Package JAR
              run: mvn package -DskipTests

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push image
              run: |
                docker build -t 43vignesh34/AssessmentAppImage .
                docker push 43vignesh34/AssessmentAppImage
            # | allows us to run multiple commands in one step
            - name: Run Integration Tests
              run: mvn verify -DskipUnitTests

    deploy:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        needs: build-and-test

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Deploy to AWS
              uses: einaregilsson/beanstalk-deploy@v21
              with:
                aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                application_name: AssessmentApplication
                environment_name: AssessmentApplication-env
                version_label: "ver-${{ github.sha }}"
                region: ap-southeast-2
    
        